### ISSUE TITLE
username does not match email address when using multiple email addresses/multiple users

### ISSUE THREAD

**Issue by rms-cjohns** [micz/ThunderStats#123]
We have many users (21 of them) setup in a single thunderbird installation.  When we run the stats it lists the top senders and receivers, and in that list it will give a persons name with a different users email address.  This is not the case with every name/address, only a few of them.  I checked the names associated with the account in thunderbird and they are correct.  It seems to be getting mixed up within thunderstats.

**Comment by micz** [comment]
Are the names completely different or similar?

If they are similar, this could happen if the same email address is used in mails with different names associated.
The problem is not about the account name that sends it, but the name used in the mails, even if received by others.
Thunderbird saves a different contact also if the mail address is the same but with a different name.

I try to explain with this example.
Consider a mail like john.smith@example.com as the recipient of a mail you send or receive.
If you receive (or send) a mail once with "J. Smith" as the name and one with "John Smith", Thunderbird will save two contacts with the same mail address, but different names.

ThunderStats will use one of them. At the moment there is no way to know which name is the "correct" one.

**Comment by rms-cjohns** [comment]
I don’t want this list getting out since it has our email addresses listed, but this is what I am referring to.  You can see the name Alycia Snow appears for the email addresses of kpiel, jkruchten, and airving.  Personally I look at this and say “meh, it’s an inconvenient bug” but the person who is compiling these stats sees it as something a little more.  It should probably be noted that Alycia was the first email address I entered into thunderbird.


[cid:image001.png@01D15213.599861B0]
Thanks,
Chris Johns

Recovery Management Services, Inc.
Phone: 630.657.5054 x208
Email: cjohns@rmscollects.com<mailto:cjohns@rmscollects.com>



CONFIDENTIALITY NOTICE
This email message, including all attachments, is for the sole use of the intended recipients and may contain confidential and privileged information.  If you are not the intended recipient, you may NOT use, disclose, copy or disseminate this information.  Please contact the sender by reply email and immediately destroy all copies of the original message including all attachments.  Even if you are the intended recipient of this email, the author requests that you not forward it to any other person without prior consent.

**Comment by micz** [comment]
If I add an option to always use the account name if present, could this be a solution?

**Comment by rms-cjohns** [comment]
I guess, as long as it displays properly right?

Thanks,
Chris Johns

Recovery Management Services, Inc.
Phone: 630.657.5054 x208
Email: cjohns@rmscollects.com<mailto:cjohns@rmscollects.com>



CONFIDENTIALITY NOTICE
This email message, including all attachments, is for the sole use of the intended recipients and may contain confidential and privileged information.  If you are not the intended recipient, you may NOT use, disclose, copy or disseminate this information.  Please contact the sender by reply email and immediately destroy all copies of the original message including all attachments.  Even if you are the intended recipient of this email, the author requests that you not forward it to any other person without prior consent.

**Comment by micz** [comment]
Ok, I'll add this feature for the next version. I'll keep track of the progress in this issue.
