### ISSUE TITLE
Not all letters?

### ISSUE THREAD

**Issue by Poccapx** [micz/ThunderStats#147]
It appears that ThunderStats don’t see all of the e-mails present in my profile:

<img src=https://user-images.githubusercontent.com/18540542/27518726-de018f80-59e6-11e7-807b-76ae093ec2f0.png width=371 height=201 />

Of that i only have one, an IMAP profile, which is working well. Where can the issue lie? I’m also using [Mail Summaries](http://addons.mozilla.org/thunderbird/addon/mail-summaries) for statistics, which do read the total letter count correctly.
​
​
_Would like to add that ThunderStats are a really great addon, something i’ve been missing in Thunderbird for many years! As a side suggestion, please add an_ all e-mails option _in the drop down menu of the Custom View tab (currently one have to manually set a date range to see stats over all of the letters one have in TB), as well as make TS remember last selected tab over restarts. Thank you!_

**Comment by micz** [comment]
Thank you for your suggestions! I've submitted issues #148 and #149.

About the wrong mail count, it could be caused by mailing lists emails. If your email is not listed in any from, to, cc fields, it is not considered, because Thunderbird can't assing it to an identity.
Mailsummaries is working because it is directly counting the emails present in the folder.
TS, instead, is using the internal Thunderbird database to count email referred to an identity.

**Comment by Poccapx** [comment]
Aye, could be that - i do receive some amount of those. Do you have a fix for that? For instance, counting letters, lacking listed fields, in a raw way like MS - to not loose them in the statistics.

**Comment by Poccapx** [comment]
I have installed TS on a different machine, with another account, and there the situation is even worse: only 161 letters out of nearly 2000 are shown. And that account almost doesn't have any mailing list letters at all. Instead it's a combination of several older accounts combined into a modern IMAP one. That's likely the problem. Mail Summaries show the right amount as last time. However it may be, with less than 10 % of the letters taken into account, the statistics from TS aren't really useful. This needs a fix.

**Comment by Poccapx** [comment]
And on that machine i did notice exactly when the problem occurs: i received 2 new letters, first addressed _directly_ to the address set in account settings of TB, and second which was sent to another account which just _redirects_ all letters to the account set in TB. Only the first letter was seen by ThunderStats. This confirms your theory about To-fields. Would you mind taking care of this issue in the future release?

**Comment by micz** [comment]
Sorry for the delay of this answer.
The only way is to create a custom database for all the emails and do not use the Thunderbird internal one.
I wanted to do this since the day one, as described in issue #9 , because it gives complete control on quite everything. It's a long and complex task, that I think I need address some day, since the majority of the problems with this extension are due to the Thunderbird internal database that has not been designed for stats crunching.
