### ISSUE TITLE
Top Senders breaks on large number of messages (~ 5455)

### ISSUE THREAD

**Issue by ChrisCheney** [micz/ThunderStats#161]
When running a 'custom view' report ThunderStats does not appear to ever populate the 'Top Senders' field if the message count is above ~ 5455 messages. When this happens it appears to break ThunderStats 'Custom View' until ThunderStats tab is closed and reopened. 

To hit this on my email account I can set it to run from 2/12/2017 (5455 messages) to 5/30/2018 and it works fine but if I set it to 2/11/2017 (5457 messages) it does not populate. It takes about 25-26s to run when it works.

thunderbird 1:52.8.0+build1-0ubuntu0.18.04.1
System: Intel i7-6700t w/ 32GB RAM

**Comment by ChrisCheney** [comment]
It also appears if 'Top Senders' is set to larger than 10 it fails even sooner.

**Comment by ChrisCheney** [comment]
Hmm, actually it seems more broken than I previously thought. If I try to change the date range prior to where it still works eg from 05/01/2017 - 05/30/2018 (3187 messages for Top Senders - 20 works) to 03/01/2017 - 05/01/2017 (only 553 messages) it fails to show any 'Top Senders'.

I've also reset global-messages-db.sqlite with no improvement.

**Comment by ChrisCheney** [comment]
![screenshot_20180530_214350](https://user-images.githubusercontent.com/5958984/40758393-b6abea6c-6452-11e8-9808-b8be02e3e96c.png)

**Comment by ChrisCheney** [comment]
Enabled some extra debugging and saw the following:
![screenshot_20180530_224253](https://user-images.githubusercontent.com/5958984/40760107-d301cee0-645a-11e8-8b79-b59f9e0fddeb.png)

**Comment by micz** [comment]
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

The addon is being rewritten from scratch with a completely different system for gathering data; therefore, I’m closing this issue.

The error was due to the SQL query with too many terms. In the new version TS will use a Thunderbird API and no more a direct query on the Thunderbird gloda database.
