### ISSUE TITLE
Export Function

### ISSUE THREAD

**Issue by npeter88** [micz/ThunderStats#74]
Please add a function to export the stats into a csv data. If possible I would be very nice to have a automatically daily report. For example if thunderbird closed, the addon create a csv data with the stats into a folder, that can be set in the addon options.

**Comment by micz** [comment]
Which information do you think could be useful in that export?

**Comment by npeter88** [comment]
I think a daily summary would be nice to have. How many emails was received and send.
And how many emails was send/received to/from internal contacts (with a domain whitelist) and how many emails was send/received to/from external contact.

example csv:
email account; emails send; emails received; send to internal; send to external; received from internal; received from external
test@example.com; 20; 25; 15; 5; 15; 10

Is it possible? I never found a report addon for thunderbird. But yours can be do it :)

**Comment by micz** [comment]
In a future version I could add an exporter with some options.
"new feature" label added.
Thank you.

**Comment by N-Leach** [comment]
Hi, 
Thanks for your message I'm sorry to hear that. 
Do you maybe have time to tell me how I could try to export the data? 
Would be great if you could point me in the right direction. 

Totally understand if you don't have time. 
Thanks in advance. 
Nina 

On 17 November 2018 at 11:22 pm, Mic <notifications@github.com> wrote:

I'm sorry, the development of all my addons has been discontinued because on every new Thunderbird version there are changes in the core that breaks how the addons work.
Too much hours are needed just to keep an addon working with new Thunderbird versions.

**Comment by micz** [comment]
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

I’ve added this issue to [Milestone 2.*](https://github.com/micz/ThunderStats/milestone/14).

**Comment by micz** [comment]
The Export funtctionality will be implemented in version 2.1.
It's possibile to follow the work from issue: https://github.com/micz/ThunderStats/issues/287.

Your suggestion has been splitted in #320 (due in 2.1) and #321 (due in a future release).

I'm now closing this issue.
Thank you.
